// <auto-generated />
namespace Bushido.Common.Data.Migrations.DemoDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DemoDbInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DemoDbInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201705141221591_DemoDbInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
